
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      open-in-view: false
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
  datasource:
    url: jdbc:h2:./db/solution
    driver-class-name: org.h2.Driver
    username: sa
    password:
#  sql:
#    init:
#      platform: h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true